### PR TITLE
Let's rock'n roll :-)

### PR DESCRIPTION
**Pull request by hawkeyexp**
Hope you enjoy new fixes and upgrades:
- Fix download of raspbian image - sometimes wget spider gets a faulty result so i added a retry
- Fix start bug of auto app caused by missing libs - rpi-update has only corrected missing links so it's
  now replaced with a simple ln -s :-)
- Configurable wifi client in dev mode - setup via environment - works well for me! (tested on 2,4GHz)
- Make sure no shutdown command will bring system down if dev mode is enabled via environment
  or gpio (you sometimes forgot gpio reading :-) - i think if dev mode is enabled the user doesn't need
  any auto shutdown cause he is "playing arround"
- Small fixes

### CODE REVIEW

**Comment by htruong** [comment]
Thanks -- On your observation of `ln -s` -- I had that exact idea, and somehow it still didn't work for me and decided to roll back that a couple of weeks before:

https://github.com/htruong/crankshaft/commit/2b480c5863e637161588090aba1343e9fe8c5b52

I guess I will have to test again.

**Comment by hawkeyexp** [comment]
It should work without probs - tried on blank lite image an noticed i forgot to link also in rpi buildscript - fixed now.
What do you think about the wifi integration ?

**Comment by htruong** [comment]
Wifi looks reasonable enough to me. I wonder if this works with WPA2 or just WPA? We'd like it to be as simple as possible, so I think this is great, but if it doesn't work with WPA2 then it's probably helpful to add WPA2 support as well. What do you think?

**Comment by hawkeyexp** [comment]
wpa_passphrase only encodes a ascii string (password) and the ssid to a valid psk in correct format to put it into the conf file. It's not dependend if connection is wpa or wpa2. In my case ap is only working in wpa2.
I also will add a customized rc.local which will show all information in a clear view.

**Comment by hawkeyexp** [comment]
How do you think about a ap-mode via hostapd in normal boot state ?

**Pull request merged**
